
// This file has been generated by the GUI designer. Do not modify.
namespace TorrentNerd
{
	public partial class MainWindow
	{
		private global::Gtk.Notebook notebook1;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Label label10;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TorrentNerd.MainWindow
			this.Name = "TorrentNerd.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Torrent Nerd");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultHeight = 630;
			// Container child TorrentNerd.MainWindow.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			// Notebook tab
			global::Gtk.Label w1 = new global::Gtk.Label ();
			w1.Visible = true;
			this.notebook1.Add (w1);
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Watch");
			this.notebook1.SetTabLabel (w1, this.label8);
			this.label8.ShowAll ();
			// Notebook tab
			global::Gtk.Label w2 = new global::Gtk.Label ();
			w2.Visible = true;
			this.notebook1.Add (w2);
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Search");
			this.notebook1.SetTabLabel (w2, this.label9);
			this.label9.ShowAll ();
			// Notebook tab
			global::Gtk.Label w3 = new global::Gtk.Label ();
			w3.Visible = true;
			this.notebook1.Add (w3);
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Daily Suggestions");
			this.notebook1.SetTabLabel (w3, this.label10);
			this.label10.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 500;
			this.Show ();
		}
	}
}
