
// This file has been generated by the GUI designer. Do not modify.
namespace TorrentNerd
{
	public partial class ChooseSubAndLocationDialog
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label lblRelease;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Image imgPoster;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label1;

		private global::Gtk.Label lblName;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label2;

		private global::Gtk.Label lblRating;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label3;

		private global::Gtk.Label lblVotes;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label4;

		private global::Gtk.Button btnLink;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView tvPlot;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label7;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvSubs;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label8;

		private global::Gtk.Button btnPath;

		private global::Gtk.Button btnDownload;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TorrentNerd.ChooseSubAndLocationDialog
			this.Name = "TorrentNerd.ChooseSubAndLocationDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TorrentNerd.ChooseSubAndLocationDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.lblRelease = new global::Gtk.Label ();
			this.lblRelease.Name = "lblRelease";
			this.lblRelease.LabelProp = global::Mono.Unix.Catalog.GetString ("N/A");
			this.hbox8.Add (this.lblRelease);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.lblRelease]));
			w2.Position = 0;
			this.vbox4.Add (this.hbox8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox8]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.imgPoster = new global::Gtk.Image ();
			this.imgPoster.Name = "imgPoster";
			this.hbox2.Add (this.imgPoster);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.imgPoster]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.hbox6.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblName = new global::Gtk.Label ();
			this.lblName.Name = "lblName";
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString ("N/A");
			this.hbox6.Add (this.lblName);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.lblName]));
			w6.Position = 1;
			this.vbox5.Add (this.hbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Rating:");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblRating = new global::Gtk.Label ();
			this.lblRating.Name = "lblRating";
			this.lblRating.LabelProp = global::Mono.Unix.Catalog.GetString ("8.5/10");
			this.hbox3.Add (this.lblRating);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblRating]));
			w9.Position = 1;
			this.vbox5.Add (this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox3]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString (" Votes:");
			this.hbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label3]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblVotes = new global::Gtk.Label ();
			this.lblVotes.Name = "lblVotes";
			this.lblVotes.LabelProp = global::Mono.Unix.Catalog.GetString ("45852");
			this.hbox4.Add (this.lblVotes);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblVotes]));
			w12.Position = 1;
			this.vbox5.Add (this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox4]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("   Link:");
			this.hbox5.Add (this.label4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btnLink = new global::Gtk.Button ();
			this.btnLink.CanFocus = true;
			this.btnLink.Name = "btnLink";
			this.btnLink.UseUnderline = true;
			this.btnLink.Label = global::Mono.Unix.Catalog.GetString ("http://www.imdb.com");
			this.hbox5.Add (this.btnLink);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnLink]));
			w15.Position = 1;
			this.vbox5.Add (this.hbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("   Plot:");
			this.hbox7.Add (this.label5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label5]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tvPlot = new global::Gtk.TextView ();
			this.tvPlot.CanFocus = true;
			this.tvPlot.Name = "tvPlot";
			this.tvPlot.Editable = false;
			this.tvPlot.CursorVisible = false;
			this.tvPlot.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add (this.tvPlot);
			this.hbox7.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.GtkScrolledWindow1]));
			w19.Position = 1;
			this.vbox5.Add (this.hbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w20.Position = 4;
			w20.Expand = false;
			w20.Fill = false;
			this.hbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox5]));
			w21.Position = 1;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
			w22.Position = 1;
			this.vbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1f;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Available subtitles:");
			this.hbox9.Add (this.label7);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label7]));
			w24.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("English"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("Slovenian"));
			this.combobox1.Name = "combobox1";
			this.combobox1.Active = 0;
			this.hbox9.Add (this.combobox1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.combobox1]));
			w25.Position = 1;
			this.vbox6.Add (this.hbox9);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvSubs = new global::Gtk.TreeView ();
			this.tvSubs.CanFocus = true;
			this.tvSubs.Name = "tvSubs";
			this.GtkScrolledWindow.Add (this.tvSubs);
			this.vbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow]));
			w28.Position = 1;
			this.vbox3.Add (this.vbox6);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox6]));
			w29.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Download location:");
			this.hbox10.Add (this.label8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label8]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.btnPath = new global::Gtk.Button ();
			this.btnPath.CanFocus = true;
			this.btnPath.Name = "btnPath";
			this.btnPath.UseUnderline = true;
			this.btnPath.Label = global::Mono.Unix.Catalog.GetString ("N/A");
			this.hbox10.Add (this.btnPath);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.btnPath]));
			w31.Position = 1;
			this.vbox7.Add (this.hbox10);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox10]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox3.Add (this.vbox7);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox7]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			w1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(w1[this.vbox3]));
			w34.Position = 0;
			// Internal child TorrentNerd.ChooseSubAndLocationDialog.ActionArea
			global::Gtk.HButtonBox w35 = this.ActionArea;
			w35.Name = "dialog1_ActionArea";
			w35.Spacing = 10;
			w35.BorderWidth = ((uint)(5));
			w35.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnDownload = new global::Gtk.Button ();
			this.btnDownload.CanFocus = true;
			this.btnDownload.Name = "btnDownload";
			this.btnDownload.UseUnderline = true;
			this.btnDownload.Label = global::Mono.Unix.Catalog.GetString ("Download");
			this.AddActionWidget (this.btnDownload, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w35[this.btnDownload]));
			w36.Expand = false;
			w36.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 500;
			this.DefaultHeight = 630;
			this.Show ();
			this.btnLink.Clicked += new global::System.EventHandler (this.openImdbLink);
			this.combobox1.Changed += new global::System.EventHandler (this.languageChanged);
			this.btnPath.Clicked += new global::System.EventHandler (this.OnBtnPathClicked);
			this.btnDownload.Clicked += new global::System.EventHandler (this.btnDownload_Clicked);
		}
	}
}
